bookshelf/data/models.py
from flask_sqlalchemy import SQLAlchemy
from flask_security import UserMixin, RoleMixin

db = SQLAlchemy()


class Book(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(80))
    rating = db.Column(db.Integer)
    image = db.Column(db.String(30))
    author_id = db.Column(db.Integer, db.ForeignKey("author.id"))
    author = db.relationship("Author", backref=db.backref("books", lazy="joined"))

    def __init__(self, title, author, image=None, rating=0):
        self.title = title
        self.author = author
        self.image = image
        self.rating = rating

    def __repr__(self):
        return "<Book %r>" % (self.title)


class Author(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    names = db.Column(db.String(100), unique=True)

    def __init__(self, names):
        self.names = names

    def __repr__(self):
        return "<Author %r>" % (self.names)


roles_users = db.Table(
    "roles_users",
    db.Column("user_id", db.Integer(), db.ForeignKey("user.id")),
    db.Column("role_id", db.Integer(), db.ForeignKey("role.id")),
)


class Role(db.Model, RoleMixin):
    id = db.Column(db.Integer(), primary_key=True)
    name = db.Column(db.String(80), unique=True)
    description = db.Column(db.String(255))

    def __init__(self, name):
        self.name = name

    def __repr__(self):
        return "<Role %r>" % (self.name)


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(255), unique=True)
    password = db.Column(db.String(255))
    active = db.Column(db.Boolean())
    roles = db.relationship(
        "Role", secondary=roles_users, backref=db.backref("users", lazy="dynamic")
    )

    def __init__(self, email, password, active, roles):
        self.email = email
        self.password = password
        self.active = active
        self.roles = roles

    def __repr__(self):
        return "<User %r>" % (self.email)

bookshelf/admin/forms/author_forms.py
from wtforms import Form, TextField, validators
from flask_babel import lazy_gettext as _


class CreateAuthorForm(Form):
    names = TextField(_("Names"), [validators.Length(min=5, max=70)])

bookshelf/__init__.py
from flask import abort, Flask, g, render_template, request, current_app
from flask_babel import Babel
from flask_security import current_user
from bookshelf.utils import get_instance_folder_path
from bookshelf.main.controllers import main
from bookshelf.admin.controllers import admin
from bookshelf.cache import cache
from bookshelf.config import configure_app
from bookshelf.data.models import db

app = Flask(
    __name__,
    instance_path=get_instance_folder_path(),
    instance_relative_config=True,
    template_folder="templates",
)

babel = Babel(app)
configure_app(app)
cache.init_app(app)
db.init_app(app)
app.jinja_env.add_extension("jinja2.ext.loopcontrols")


@app.url_defaults
def set_language_code(endpoint, values):
    if "lang_code" in values or not g.get("lang_code", None):
        return
    if app.url_map.is_endpoint_expecting(endpoint, "lang_code"):
        values["lang_code"] = g.lang_code


@app.url_value_preprocessor
def get_lang_code(endpoint, values):
    if values is not None:
        g.lang_code = values.pop("lang_code", None)


@app.before_request
def ensure_lang_support():
    lang_code = g.get("lang_code", None)
    if lang_code and lang_code not in app.config["SUPPORTED_LANGUAGES"].keys():
        abort(404)


@babel.localeselector
def get_locale():
    return g.get("lang_code", app.config["BABEL_DEFAULT_LOCALE"])


@babel.timezoneselector
def get_timezone():
    user = g.get("user", None)
    if user is not None:
        return user.timezone
    return "UTC"


@app.errorhandler(404)
def page_not_found(error):
    current_app.logger.error("Page not found: %s", (request.path, error))
    return render_template("404.htm"), 404


@app.errorhandler(500)
def internal_server_error(error):
    current_app.logger.error("Server Error: %s", (error))
    return render_template("500.htm"), 500


@app.errorhandler(Exception)
def unhandled_exception(error):
    current_app.logger.error("Unhandled Exception: %s", (error))
    return render_template("500.htm"), 500


@app.context_processor
def inject_data():
    return dict(user=current_user, lang_code=g.get("lang_code", None))


@app.route("/")
@app.route("/<lang_code>/")
@cache.cached(300)
def home(lang_code=None):
    return render_template("index.htm")


app.register_blueprint(main, url_prefix="/main")
app.register_blueprint(main, url_prefix="/<lang_code>/main")
app.register_blueprint(admin, url_prefix="/admin")
app.register_blueprint(admin, url_prefix="/<lang_code>/admin")

bookshelf/admin/controllers.py
from sqlalchemy import exc
from flask import Blueprint, render_template, flash
from flask import current_app, redirect, request, url_for
from flask_security.decorators import roles_required
from bookshelf.admin.forms.author_forms import CreateAuthorForm
from bookshelf.cache import cache
from bookshelf.data.models import Author, db


admin = Blueprint("admin", __name__, template_folder="templates")


@admin.route("/")
@roles_required("admin")
def index():
    return render_template("admin_index.htm")


@admin.route("/author/create", methods=["GET", "POST"])
@roles_required("admin")
def create_author():
    form = CreateAuthorForm(request.form)
    if request.method == "POST" and form.validate():
        names = form.names.data
        current_app.logger.info("Adding a new author %s.", (names))
        author = Author(names)

        try:
            db.session.add(author)
            db.session.commit()
            cache.clear()
            flash("Author successfully created.")
        except exc.SQLAlchemyError as e:
            flash("Author was not created.")
            current_app.logger.error(e)

            return redirect(url_for("admin.create_author"))

        return redirect(url_for("main.display_authors"))

    return render_template("create_author.htm", form=form)

bookshelf/main/controllers.py
from flask import Blueprint, current_app, render_template
from bookshelf.cache import cache
from bookshelf.data.models import Author, Book


main = Blueprint("main", __name__, template_folder="templates")


@main.route("/books/")
@cache.cached(300)
def display_books():
    books = [book for book in Book.query.all()]
    current_app.logger.info("Displaying all books.")

    return render_template("books.htm", books=books)


@main.route("/authors/")
@cache.cached(300)
def display_authors():
    authors = [author for author in Author.query.all()]
    current_app.logger.info("Displaying all authors.")

    return render_template("authors.htm", authors=authors)

bookshelf/templates/404.htm
{% extends 'layout.htm' %}
{% block container %}
  <h2>Page Not Found</h2>
{% endblock %}

bookshelf/templates/500.htm
{% extends 'layout.htm' %}
{% block container %}
  <h2>Something Went Wrong</h2>
{% endblock %}

bookshelf/templates/index.htm
{% extends 'layout.htm' %}
{% block container %}
  <div class="top-pad">
    {{ _('Flask Bookshelf') }}
  </div>
{% endblock %}

bookshelf/templates/layout.htm
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initialscale=1">
  <title>Flask Bookshelf</title>
  <meta charset="utf-8">
  <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='css/main.css') }}" rel="stylesheet">
  <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
</head>

<body>

  <nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="{{ url_for('home') }}">{{ _('Flask Bookshelf') }}</a>
      </div>
      <div>
        <ul class="nav navbar-nav">
          <li>
            <a class="navbar-brand" href="{{ url_for('main.display_authors') }}">{{ _('Authors') }}</a>
          </li>
          <li>
            <a class="navbar-brand" href="{{ url_for('main.display_books') }}">{{ _('Books') }}</a>
          </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          {% if user.has_role('admin') %}
          <li>
            <a class="navbar-brand" href="{{ url_for('admin.index') }}">{{ _('Admin') }}</a>
          </li>
          {% endif %} {% if not user.is_authenticated %}
          <li>
            <a href="/login">
              <span class="glyphicon glyphicon-log-in"></span> {{ _('Log In') }}</a>
          </li>
          {% else %}
          <li>
            <a href="/logout">
              <span class="glyphicon glyphicon-log-out"></span> {{ _('Log Out') }}</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    {% with messages = get_flashed_messages() %} {% if messages %}
    <ul class="flashes">
      {% for message in messages %}
      <li>{{ message }}</li>
      {% endfor %}
    </ul>
    <br/> {% endif %} {% endwith %} {% block container %}{% endblock %}
  </div>
  <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js"></script>
  <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
</body>

</html>

bookshelf/templates/security/login_user.html
{% extends 'layout.htm' %}
{% block container %}
  {% from "security/_macros.html" import render_field_with_errors, render_field %}
  {% include "security/_messages.html" %}
  <h1>Login</h1>
  <form action="{{ url_for_security('login') }}" method="POST" name="login_user_form">
  {{ login_user_form.hidden_tag() }}
  {{ render_field_with_errors(login_user_form.email) }}
  {{ render_field_with_errors(login_user_form.password) }}
  {{ render_field_with_errors(login_user_form.remember) }}
  {{ render_field(login_user_form.next) }}
  {{ render_field(login_user_form.submit) }}
  </form>
{% endblock %}

bookshelf/templates/security/register_user.html
{% extends 'layout.htm' %}
{% block container %}
  {% from "security/_macros.html" import render_field_with_errors, render_field %}
  {% include "security/_messages.html" %}
  <h1>Register</h1>
  <form action="{{ url_for_security('register') }}" method="POST" name="register_user_form">
    {{ register_user_form.hidden_tag() }}
    {{ render_field_with_errors(register_user_form.email) }}
    {{ render_field_with_errors(register_user_form.password) }}
    {% if register_user_form.password_confirm %}
      {{ render_field_with_errors(register_user_form.password_confirm) }}
    {% endif %}
    {{ render_field(register_user_form.submit) }}
  </form>
{% endblock %}